//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlaBlaCarV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTHENTIFICATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AUTHENTIFICATION()
        {
            this.MESSAGERIEs = new HashSet<MESSAGERIE>();
            this.MESSAGERIEs1 = new HashSet<MESSAGERIE>();
            this.PROFILs = new HashSet<PROFIL>();
            this.RESERVATIONs = new HashSet<RESERVATION>();
            this.TRAJETs = new HashSet<TRAJET>();
        }
    
        public int ID_AUTHENTIFICATION { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public decimal JOUR { get; set; }
        public decimal MOIS { get; set; }
        public decimal ANNEE { get; set; }
        public bool SEXE { get; set; }
        public decimal TELEPHONE { get; set; }
        public string USERNAME { get; set; }
        public string PASS { get; set; }
        public string VILLE { get; set; }
        public bool VISIBILITETELEPHONE { get; set; }
        public bool NEWSLETTRE { get; set; }
        public string PICTURE { get; set; }
        public string CODE_ACTIVATION { get; set; }
        public bool COMPTE_ACTIVE { get; set; }
        public System.DateTime DATE_INSCRIPTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MESSAGERIE> MESSAGERIEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MESSAGERIE> MESSAGERIEs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROFIL> PROFILs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVATION> RESERVATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAJET> TRAJETs { get; set; }
    }
}
