//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlaBlaCarV2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlaBlaCarDBContext : DbContext
    {
        public BlaBlaCarDBContext()
            : base("name=BlaBlaCarDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTHENTIFICATION> AUTHENTIFICATIONs { get; set; }
        public virtual DbSet<MESSAGERIE> MESSAGERIEs { get; set; }
        public virtual DbSet<PROFIL> PROFILs { get; set; }
        public virtual DbSet<RESERVATION> RESERVATIONs { get; set; }
        public virtual DbSet<TRAJET> TRAJETs { get; set; }
    }
}
