//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlaBlaCarV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFIL
    {
        public int ID_PROFIL { get; set; }
        public int ID_AUTHENTIFICATION { get; set; }
        public bool MUSIQUE { get; set; }
        public bool FUMEUR { get; set; }
        public bool ANIMAUX { get; set; }
        public bool DISCUSSION { get; set; }
        public bool DETOUR { get; set; }
        public string ADRESSE_1 { get; set; }
        public string ADRESSE_2 { get; set; }
        public decimal CODE_POSTAL { get; set; }
        public string PAYS { get; set; }
        public string MARQUE_VOITURE { get; set; }
        public string MODELE_VOITURE { get; set; }
        public string CONFORT_VOITURE { get; set; }
        public Nullable<int> NOMBRE_PLACE_VOITURE { get; set; }
        public bool PAS_DE_VOITURE { get; set; }
    
        public virtual AUTHENTIFICATION AUTHENTIFICATION { get; set; }
    }
}
