//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlaBlaCarV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATION
    {
        public int ID_RESERVATION { get; set; }
        public int ID_AUTHENTIFICATION { get; set; }
        public int ID_TRAJET { get; set; }
    
        public virtual AUTHENTIFICATION AUTHENTIFICATION { get; set; }
        public virtual TRAJET TRAJET { get; set; }
    }
}
