//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlaBlaCarV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAJET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRAJET()
        {
            this.RESERVATIONs = new HashSet<RESERVATION>();
        }
    
        public int ID_TRAJET { get; set; }
        public int ID_AUTHENTIFICATION { get; set; }
        public string TYPE_UTILISATEUR { get; set; }
        public string VILLE_DEPART { get; set; }
        public decimal CP_D { get; set; }
        public string LIEUX_A { get; set; }
        public System.DateTime LA_DATE { get; set; }
        public System.TimeSpan HEURE { get; set; }
        public decimal NBR_PLACES_DISPO { get; set; }
        public decimal NBR_RESERVATIONS { get; set; }
        public bool HOMME { get; set; }
        public bool FEMME { get; set; }
        public bool BAGAGE { get; set; }
        public bool COlIS { get; set; }
        public bool FUMEUR_OUI { get; set; }
        public bool FUMEUR_NON { get; set; }
        public bool HANDICAPE { get; set; }
        public bool ANIMAUX { get; set; }
        public decimal PRIX { get; set; }
        public System.DateTime DATE_JOUR { get; set; }
        public System.DateTime DATE_VOYAGE { get; set; }
    
        public virtual AUTHENTIFICATION AUTHENTIFICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVATION> RESERVATIONs { get; set; }
    }
}
